version: '3'
services:

  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    volumes: 
      - db:/var/lib/postgresql/data
  redis:
    container_name: redis-leal
    image: 'redis:alpine'
    ports:
      - '6379:6379'

  redis-commander:
    container_name: redis-commander-leal
    hostname: redis-commander
    image: spryker/redis-commander:0.8.0
    restart: always
    environment:
      - REDIS_HOSTS=local:redis:6379
    ports:
      - "8082:8081"
    depends_on:
      - redis
volumes:
  db:
    driver: local
networks:
  services_aval_soluciones_digitales:
    external: false